# Generated by Django 3.0.7 on 2021-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=255)),
                ('distance', models.FloatField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('points', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
